### ISSUE TITLE
Not displaying in text above character anymore.

### ISSUE THREAD

**Issue by ithankyousomuch** [OzokuLight/self-healing-notifications#2]
https://i.imgur.com/sfoppDp.png
This plugin has stopped working for me. 

It used to look like this: https://i.imgur.com/Rb9MM6b.mp4 (stating how much you healed above your character in text), but now it only announces the amount healed in chatbox.

**Comment by OzokuLight** [comment]
Make sure you have display sent to Simple or Default, otherwise it just shows in textbox. I did just test on the live version of the plugin and it is working for me.

**Comment by ithankyousomuch** [comment]
Hey, it works again, im not sure why but ty for plugin and response. 
Think switching runelite profile back and forth fucked me, like theres always some plugins that dont work after having switched. Not until reboot that is.

Anyway ty!
